---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list: 
    - recipe[gitlab-ci]
    attributes: 
      postfix:
        mail_type: client
        myhostname: mail.localhost
        mydomain: localhost
        myorigin: mail.localhost
        smtp_use_tls: no
      gitlab_ci:
        database_adapter: mysql
        database_password: gitlab
      mysql:
        server_debian_password: test
        server_repl_password: test
        server_root_password: test
